In [65]:
import pandas as pd
import statsmodels.api as sm
from statsmodels.iolib.summary2 import summary_col
from tabulate import  tabulate
import numpy as np
import plotly.express as px
from stats.reg import compute_vif

In [66]:
panel_in = "../../../data/final/model_data.parquet"

did_out = "../../../reports/replication/did.md"
fe_out = "../../../reports/replication/fe.md"
parallel_out = "../../../reports/replication/parallel_trends.jpeg"

In [67]:
panel = pd.read_parquet(panel_in)

# Preprocessing

In [68]:
panel['logrides'] = panel['rides'].apply(np.log1p)

In [69]:
dotw_names = {f"C(dotw)[T.{i}]":j for i,j in zip([1,2,3,4],['Tuesday','Wednesday','Thursday','Friday'])}

# Fixed Effects

In [70]:
def mask_colinear(df, groupby, coef):
    test = df.groupby(groupby)[coef].nunique() > 1
    mask = df[groupby].isin(test[test].index)
    if not all(test):
        print(f"Dropping {sum(~test)} {groupby}, {sum(~mask)} obs invariant to {coef}")
    return mask

def model_fe(df):
    ## Community areas dont have separate units for transit.
    ## Since fixed effects cant distringuish transit anyway,
    ## Might as well sum it. Otherwise you have huge variance per unit.
    df = df.groupby(['id','date','dotw','DNC'])['rides'].sum().reset_index()
    df = df.sort_values('date')
    df['time'] = pd.Categorical(df['date']).codes
    # Make sure all units have variance in all coefs.
    mask = np.full_like(df.index, True)
    for coef in ['DNC','time','dotw']:
        mask &= mask_colinear(df, 'id', coef)
    df = df[mask]
    id_formula = "C(id)" #catvar(df, "id", tract_panel.id.min())
    formula = f"""np.log1p(rides) ~ 
                DNC + time + C(dotw) + {id_formula}"""
    model = sm.OLS.from_formula(formula, df).fit()
    return model

In [71]:
def print_fe(model):
    for l in str(model.summary()).split('\n'):
        if not l.startswith('C(id)'):
            print(l)

In [72]:
model_data = panel.loc[panel.transit == 'train']
train_fe_model = model_fe(model_data)
print_fe(train_fe_model)

                            OLS Regression Results
==============================================================================
Dep. Variable:        np.log1p(rides)   R-squared:                       0.772
Model:                            OLS   Adj. R-squared:                  0.768
Method:                 Least Squares   F-statistic:                     170.0
Date:                Sat, 08 Feb 2025   Prob (F-statistic):               0.00
Time:                        15:36:43   Log-Likelihood:                -1240.3
No. Observations:                1280   AIC:                             2533.
Df Residuals:                    1254   BIC:                             2667.
Df Model:                          25
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept          7.5968      0.092     82.149      0.000       7.415       7.778
C(dotw)[T.1]       0.1211      0.057      2.127      0.034       0.009       0.233
C(dotw)[T.2]       0.1351      0.057      2.370      0.018       0.023       0.247
C(dotw)[T.3]       0.0936      0.057      1.641      0.101      -0.018       0.205
C(dotw)[T.4]       0.1126      0.058      1.955      0.051      -0.000       0.226
DNC                0.1360      0.080      1.702      0.089      -0.021       0.293
time               0.0046      0.001      4.411      0.000       0.003       0.007
==============================================================================
Omnibus:                      448.842   Durbin-Watson:                   1.945
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            22589.700
Skew:                           0.837   Prob(JB):                         0.00
Kurtosis:                      23.512   Cond. No.                         760.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [73]:
compute_vif(train_fe_model)

        coef        vif
0  Intercept  26.374967

In [74]:
model_data = panel.loc[panel.transit == 'uber']
uber_fe_model = model_fe(model_data)
print_fe(uber_fe_model)

                            OLS Regression Results
==============================================================================
Dep. Variable:        np.log1p(rides)   R-squared:                       0.940
Model:                            OLS   Adj. R-squared:                  0.939
Method:                 Least Squares   F-statistic:                     942.8
Date:                Sat, 08 Feb 2025   Prob (F-statistic):               0.00
Time:                        15:36:44   Log-Likelihood:                -2886.7
No. Observations:                6718   AIC:                             5993.
Df Residuals:                    6608   BIC:                             6743.
Df Model:                         109
Covariance Type:            nonrobust
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept                  6.4213      0.048    133.847      0.000       6.327       6.515
C(dotw)[T.1]               0.1870      0.014     12.912      0.000       0.159       0.215
C(dotw)[T.2]               0.3149      0.014     21.771      0.000       0.287       0.343
C(dotw)[T.3]               0.4435      0.014     30.590      0.000       0.415       0.472
C(dotw)[T.4]               0.7877      0.015     53.860      0.000       0.759       0.816
DNC                        0.0036      0.020      0.174      0.862      -0.037       0.044
time                       0.0013      0.000      4.855      0.000       0.001       0.002
==============================================================================
Omnibus:                     1142.133   Durbin-Watson:                   1.847
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            12171.876
Skew:                           0.488   Prob(JB):                         0.00
Kurtosis:                       9.522   Cond. No.                     3.86e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.86e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [75]:
# takes forever
# # compute_vif(uber_fe_model)

In [76]:
model_data = panel.loc[panel.transit == 'bike']
bike_fe_model = model_fe(model_data)
print_fe(bike_fe_model)

Dropping 8 id, 252 obs invariant to DNC
Dropping 2 id, 2 obs invariant to time
Dropping 2 id, 2 obs invariant to dotw
                            OLS Regression Results
==============================================================================
Dep. Variable:        np.log1p(rides)   R-squared:                       0.892
Model:                            OLS   Adj. R-squared:                  0.890
Method:                 Least Squares   F-statistic:                     477.8
Date:                Sat, 08 Feb 2025   Prob (F-statistic):               0.00
Time:                        15:36:44   Log-Likelihood:                -2511.1
No. Observations:                7026   AIC:                             5262.
Df Residuals:                    6906   BIC:                             6085.
Df Model:                         119
Covariance Type:            nonrobust
=================================================================================================================
                                                    coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------------------
Intercept                                         4.5991      0.045    103.143      0.000       4.512       4.687
C(dotw)[T.1]                                      0.0257      0.013      1.956      0.050   -5.37e-05       0.052
C(dotw)[T.2]                                      0.1740      0.013     13.200      0.000       0.148       0.200
C(dotw)[T.3]                                      0.0871      0.013      6.607      0.000       0.061       0.113
C(dotw)[T.4]                                      0.1821      0.013     13.690      0.000       0.156       0.208
DNC                                               0.1416      0.018      7.708      0.000       0.106       0.178
time                                              0.0011      0.000      4.611      0.000       0.001       0.002
==============================================================================
Omnibus:                     2340.716   Durbin-Watson:                   1.774
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            31765.471
Skew:                          -1.211   Prob(JB):                         0.00
Kurtosis:                      13.131   Cond. No.                     4.17e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.17e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [77]:
# Takes forever
# # compute_vif(bike_fe_model)

In [78]:
fe_summary = summary_col([uber_fe_model, train_fe_model, bike_fe_model], 
            model_names=["FE (Uber)", "FE (Train)", "FE (Bike)"], 
            info_dict={"N":lambda x:(x.nobs)},
            stars=True,
            regressor_order=['DNC','time'] + list(dotw_names.keys()),
            drop_omitted=True)

fe_summary.tables[0].index = (fe_summary.tables[0].index
                              .map(lambda x: dotw_names[x] if x in dotw_names else x)
                              .str.replace('DNC','During DNC')
                              .str.replace('time','time trend'))

fe_table = tabulate(fe_summary.tables[0],
                   headers=["", "FE (Uber)", "FE (Train)", "FE (Bike)"],
                   showindex=True,
                   tablefmt='github')
print(fe_table)
with open(fe_out,"w") as f:
    f.write(fe_table)
!cp {fe_out} ../../../../eric-mc2-cv/static/uploads/

|                | FE (Uber)   | FE (Train)   | FE (Bike)   |
|----------------|-------------|--------------|-------------|
| During DNC     | 0.0036      | 0.1360*      | 0.1416***   |
|                | (0.0205)    | (0.0799)     | (0.0184)    |
| time trend     | 0.0013***   | 0.0046***    | 0.0011***   |
|                | (0.0003)    | (0.0010)     | (0.0002)    |
| Tuesday        | 0.1870***   | 0.1211**     | 0.0257*     |
|                | (0.0145)    | (0.0570)     | (0.0131)    |
| Wednesday      | 0.3149***   | 0.1351**     | 0.1740***   |
|                | (0.0145)    | (0.0570)     | (0.0132)    |
| Thursday       | 0.4435***   | 0.0936       | 0.0871***   |
|                | (0.0145)    | (0.0570)     | (0.0132)    |
| Friday         | 0.7877***   | 0.1126*      | 0.1821***   |
|                | (0.0146)    | (0.0576)     | (0.0133)    |
| R-squared      | 0.9396      | 0.7722       | 0.8917      |
| R-squared Adj. | 0.9386      | 0.7676       | 0.8898      |
| N              | 6718.0      | 1280.0       | 7026.0      |

In [79]:
main_effect = fe_summary.tables[0].xs('During DNC').str.replace('*','').astype(float)
main_pct = np.exp(main_effect) - 1
main_pct.apply("{:.1%}".format)

FE (Uber)      0.4%
FE (Train)    14.6%
FE (Bike)     15.2%
Name: During DNC, dtype: object

# DiffNDiff

In [80]:
def did_colinearity(df):
    mask = np.full_like(df.index, True)
    mask &= mask_colinear(df, 'id', 'DNC')
    mask &= mask_colinear(df, 'date', 'UCMP')
    df = df.loc[mask]
    return df

def model_transit_did(df, transit):
    df = df.sort_values('date')
    df['time'] = pd.Categorical(df['date']).codes
    # contained_terms = ['train_contained','bike_contained','bus_contained']
    # contained_term = " + ".join([c for c in contained_terms if c in df.columns])
    # contained_term = contained_term if contained_term else "1"
    unit_obs = df.groupby('id').size()
    df['weight'] = df['id'].map(unit_obs).apply(lambda x: 1/x)
    dist_terms = ['log_train_distance','log_bike_distance','log_bus_distance']
    dist_terms = [c for c in dist_terms if c in df.columns and transit not in c]
    dist_term = " + ".join(dist_terms)
    dist_term = dist_term if dist_term else "1"
    # Assert that spatial units have time variance (only need to test group inclusion, not every variable.)
    df = did_colinearity(df)

    formula = f"""logrides ~ 
                UCMP * DNC +
                time + C(dotw) +
                {dist_term} +
                lat + long + I(lat * long) 
                + I(lat**2) + I(long**2)
                """
    did_model = sm.WLS.from_formula(formula, df, weights=df['weight']).fit(cov_type='cluster',cov_kwds={'groups': df['id']})
    return did_model

In [81]:
model_data = panel.loc[panel.transit == 'bike']
bike_did_model = model_transit_did(model_data, 'bike')
bike_did_model.summary()

Dropping 8 id, 252 obs invariant to DNC

<class 'statsmodels.iolib.summary.Summary'>
"""
                            WLS Regression Results
==============================================================================
Dep. Variable:               logrides   R-squared:                       0.473
Model:                            WLS   Adj. R-squared:                  0.472
Method:                 Least Squares   F-statistic:                     28.70
Date:                Sat, 08 Feb 2025   Prob (F-statistic):           1.28e-31
Time:                        15:36:46   Log-Likelihood:                -8793.6
No. Observations:                7026   AIC:                         1.762e+04
Df Residuals:                    7010   BIC:                         1.773e+04
Df Model:                          15
Covariance Type:              cluster
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept              3.8425      0.505      7.609      0.000       2.853       4.832
C(dotw)[T.1]           0.0402      0.030      1.350      0.177      -0.018       0.099
C(dotw)[T.2]           0.1791      0.024      7.525      0.000       0.132       0.226
C(dotw)[T.3]           0.1241      0.037      3.326      0.001       0.051       0.197
C(dotw)[T.4]           0.1457      0.032      4.561      0.000       0.083       0.208
UCMP                  -0.0082      0.178     -0.046      0.963      -0.357       0.341
DNC                   -0.0957      0.074     -1.299      0.194      -0.240       0.049
UCMP:DNC               0.4492      0.105      4.287      0.000       0.244       0.655
time                  -0.0038      0.002     -1.990      0.047      -0.008   -5.64e-05
log_train_distance     0.1952      0.053      3.713      0.000       0.092       0.298
log_bus_distance      -0.0679      0.101     -0.673      0.501      -0.266       0.130
lat                    0.9402      0.094     10.054      0.000       0.757       1.123
long                   0.5576      0.094      5.952      0.000       0.374       0.741
I(lat * long)         -0.0103      0.152     -0.068      0.946      -0.308       0.287
I(lat ** 2)           -0.7882      0.120     -6.556      0.000      -1.024      -0.553
I(long ** 2)          -0.0392      0.073     -0.535      0.593      -0.183       0.104
==============================================================================
Omnibus:                     4045.547   Durbin-Watson:                   1.599
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            64528.535
Skew:                          -2.436   Prob(JB):                         0.00
Kurtosis:                      17.025   Cond. No.                         350.
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)
"""

In [82]:
model_data = panel.loc[panel.transit == 'train']
train_did_model = model_transit_did(model_data, 'train')
train_did_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            WLS Regression Results
==============================================================================
Dep. Variable:               logrides   R-squared:                       0.423
Model:                            WLS   Adj. R-squared:                  0.416
Method:                 Least Squares   F-statistic:                     40.78
Date:                Sat, 08 Feb 2025   Prob (F-statistic):           2.93e-11
Time:                        15:36:46   Log-Likelihood:                -1973.9
No. Observations:                1280   AIC:                             3980.
Df Residuals:                    1264   BIC:                             4062.
Df Model:                          15
Covariance Type:              cluster
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept             5.1339      2.502      2.052      0.040       0.229      10.038
C(dotw)[T.1]          0.1200      0.024      5.026      0.000       0.073       0.167
C(dotw)[T.2]          0.1357      0.024      5.549      0.000       0.088       0.184
C(dotw)[T.3]          0.1006      0.019      5.362      0.000       0.064       0.137
C(dotw)[T.4]          0.1262      0.029      4.295      0.000       0.069       0.184
UCMP                  0.1569      0.456      0.344      0.731      -0.738       1.052
DNC                  -0.1447      0.098     -1.476      0.140      -0.337       0.047
UCMP:DNC              0.8982      0.620      1.449      0.147      -0.317       2.113
time                  0.0027      0.003      0.847      0.397      -0.004       0.009
log_bike_distance     0.5530      0.348      1.592      0.111      -0.128       1.234
log_bus_distance     -0.0356      0.173     -0.206      0.837      -0.374       0.303
lat                   0.9342      0.352      2.654      0.008       0.244       1.624
long                  0.9781      0.520      1.880      0.060      -0.041       1.998
I(lat * long)         0.3624      0.380      0.954      0.340      -0.382       1.107
I(lat ** 2)          -0.1376      0.318     -0.432      0.665      -0.761       0.486
I(long ** 2)         -0.1482      0.446     -0.332      0.740      -1.022       0.726
==============================================================================
Omnibus:                      817.842   Durbin-Watson:                   2.041
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            10181.062
Skew:                          -2.810   Prob(JB):                         0.00
Kurtosis:                      15.622   Cond. No.                         353.
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)
"""

In [83]:
model_data = panel.loc[panel.transit == 'uber']
uber_did_model = model_transit_did(model_data, 'uber')
uber_did_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            WLS Regression Results
==============================================================================
Dep. Variable:               logrides   R-squared:                       0.518
Model:                            WLS   Adj. R-squared:                  0.517
Method:                 Least Squares   F-statistic:                     56.52
Date:                Sat, 08 Feb 2025   Prob (F-statistic):           1.52e-43
Time:                        15:36:46   Log-Likelihood:                -9953.4
No. Observations:                6718   AIC:                         1.994e+04
Df Residuals:                    6701   BIC:                         2.006e+04
Df Model:                          16
Covariance Type:              cluster
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept              5.5683      1.981      2.811      0.005       1.685       9.451
C(dotw)[T.1]           0.1985      0.018     11.240      0.000       0.164       0.233
C(dotw)[T.2]           0.3058      0.019     16.383      0.000       0.269       0.342
C(dotw)[T.3]           0.4434      0.024     18.761      0.000       0.397       0.490
C(dotw)[T.4]           0.7791      0.035     22.274      0.000       0.711       0.848
UCMP                   0.6760      0.396      1.707      0.088      -0.100       1.452
DNC                   -0.1139      0.041     -2.766      0.006      -0.195      -0.033
UCMP:DNC               0.2746      0.085      3.216      0.001       0.107       0.442
time                   0.0014      0.000      3.593      0.000       0.001       0.002
log_train_distance    -0.2957      0.199     -1.482      0.138      -0.687       0.095
log_bike_distance      0.1554      0.310      0.501      0.617      -0.453       0.764
log_bus_distance       0.2676      0.144      1.862      0.063      -0.014       0.549
lat                    1.1946      0.166      7.203      0.000       0.870       1.520
long                   1.0957      0.152      7.208      0.000       0.798       1.394
I(lat * long)          0.4894      0.185      2.638      0.008       0.126       0.853
I(lat ** 2)           -0.7732      0.261     -2.959      0.003      -1.285      -0.261
I(long ** 2)          -0.0143      0.105     -0.136      0.892      -0.220       0.192
==============================================================================
Omnibus:                       50.259   Durbin-Watson:                   1.334
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               73.679
Skew:                          -0.063   Prob(JB):                     1.00e-16
Kurtosis:                       3.498   Cond. No.                         778.
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)
"""

In [84]:
headers = ["DiD (Uber)", "DiD (Train)", "DiD (Bike)"]
did_summary = summary_col([uber_did_model, train_did_model, bike_did_model], 
            model_names=headers, 
            info_dict={"N":lambda x:(x.nobs)},
            stars=True,
            regressor_order=['UCMP','DNC','UCMP:DNC'] + 
                            #  ['time'] + list(dotw_names.keys()) +
                             ['log_train_distance','log_bike_distance','log_bus_distance'],
                            #  'lat','long','I(lat * long)','I(lat ** 2)', 'I(long ** 2)'],
            drop_omitted=True)

did_summary.tables[0].index = (did_summary.tables[0].index
                               .str.replace('DNC','During DNC')
                               .str.replace('UCMP','Near DNC')
                               .str.replace('time','time trend')
                               .map(lambda x: dotw_names[x] if x in dotw_names else x)
                               .str.replace('log_train_distance','log(dist to train)')
                               .str.replace('log_bike_distance','log(dist to bike)')
                               .str.replace('log_bus_distance','log(dist to bus)')
                               .str.replace('I(lat ** 2)','lat**2')
                               .str.replace('I(long ** 2)','long**2')
                               .str.replace('I(lat * long)','lat*long'))

did_table = tabulate(did_summary.tables[0],
                   headers=[""] + headers,
                   showindex=True,
                   tablefmt='github')
print(did_table)
with open(did_out,"w") as f:
    f.write(did_table)
!cp {did_out} ../../../../eric-mc2-cv/static/uploads/

|                     | DiD (Uber)   | DiD (Train)   | DiD (Bike)   |
|---------------------|--------------|---------------|--------------|
| Near DNC            | 0.6760*      | 0.1569        | -0.0082      |
|                     | (0.3960)     | (0.4565)      | (0.1781)     |
| During DNC          | -0.1139***   | -0.1447       | -0.0957      |
|                     | (0.0412)     | (0.0980)      | (0.0737)     |
| Near DNC:During DNC | 0.2746***    | 0.8982        | 0.4492***    |
|                     | (0.0854)     | (0.6198)      | (0.1048)     |
| log(dist to train)  | -0.2957      |               | 0.1952***    |
|                     | (0.1995)     |               | (0.0526)     |
| log(dist to bike)   | 0.1554       | 0.5530        |              |
|                     | (0.3104)     | (0.3475)      |              |
| log(dist to bus)    | 0.2676*      | -0.0356       | -0.0679      |
|                     | (0.1437)     | (0.1728)      | (0.1009)     |
| R-squared           | 0.5182       | 0.4228        | 0.4733       |
| R-squared Adj.      | 0.5170       | 0.4159        | 0.4722       |
| N                   | 6718.0       | 1280.0        | 7026.0       |

## DiD Impact

In [85]:
beta1 = did_summary.tables[0].xs('During DNC').str.replace('*','').astype(float)
main_pct = np.exp(beta1) - 1
pct1 = main_pct.apply("{:.1%}".format)

beta2 = did_summary.tables[0].xs('Near DNC').str.replace('*','').astype(float)
main_pct = np.exp(beta2) - 1
pct2 = main_pct.apply("{:.1%}".format)

beta3 = did_summary.tables[0].xs('Near DNC:During DNC').str.replace('*','').astype(float)
main_pct = np.exp(beta3) - 1
pct3 = main_pct.apply("{:.1%}".format)
pd.concat([pct1,pct2,pct3],axis=1)

            During DNC Near DNC Near DNC:During DNC
DiD (Uber)      -10.8%    96.6%               31.6%
DiD (Train)     -13.5%    17.0%              145.5%
DiD (Bike)       -9.1%    -0.8%               56.7%

## Contextualized Effect

In [86]:
n_trt = panel[(panel.UCMP==1)&(panel.DNC==1)].groupby('transit').size()
n_ctl = panel[(panel.UCMP==0)&(panel.DNC==1)].groupby('transit').size()
mean_trt = panel[(panel.UCMP==1)&(panel.DNC==0)].groupby(['transit','id'])['rides'].mean().groupby('transit').mean()
mean_ctl = panel[(panel.UCMP==0)&(panel.DNC==0)].groupby(['transit','id'])['rides'].mean().groupby('transit').mean()
# The geom mean vastly under-estimates the scale of the changes. because the total changes
# are in fact driven by the high-ridership tail of the distribution, which is discounted in the geom mean.
geo_mean_trt = panel[(panel.UCMP==1)&(panel.DNC==0)].groupby(['transit','id'])['logrides'].mean().groupby('transit').mean()
geo_mean_ctl = panel[(panel.UCMP==0)&(panel.DNC==0)].groupby(['transit','id'])['logrides'].mean().groupby('transit').mean()
exp_mean_trt = np.exp(geo_mean_trt)
exp_mean_ctl = np.exp(geo_mean_ctl)
pct_trt = (np.exp(beta3) - 1)
pct_ctl = (np.exp(beta1) - 1)
pct_trt.index = pct_trt.index.map(lambda x: x.replace('DiD (','').replace(')','').lower())
pct_ctl.index = pct_ctl.index.map(lambda x: x.replace('DiD (','').replace(')','').lower())
delta_trt = pct_trt * mean_trt * n_trt
delta_ctl = pct_ctl * mean_ctl * n_ctl
tmp = pd.DataFrame({'trt':delta_trt, 'ctl':delta_ctl}).round(0)
delta_trt = pct_trt * geo_mean_trt * n_trt
delta_ctl = pct_ctl * geo_mean_ctl * n_ctl
tmp2 = pd.DataFrame({'geotrt':delta_trt, 'geoctl':delta_ctl}).round(0)
pd.concat([tmp,tmp2],axis=1)

           trt      ctl  geotrt  geoctl
bike    6505.0  -1880.0   379.0   -93.0
train  93994.0 -20035.0   317.0   -50.0
uber   46671.0 -20205.0   288.0  -149.0

## Parallel Trends

PT is actually pretty convincing.

In [87]:
plot_data = panel.assign(nearby = panel['UCMP'].map({0:False, 1:True}))
plot_data = did_colinearity(plot_data)
plot_data = plot_data.groupby(['date','nearby','transit'])['rides'].sum().reset_index()
means = plot_data.groupby(['nearby','transit'])['rides'].mean().rename('mean').reset_index()
first = plot_data.sort_values('date')[['nearby','transit','rides']].iloc[:6].rename(columns={'rides':'first'})
plot_data = plot_data.merge(means, on=['nearby','transit']).merge(first, on=['nearby','transit'])
plot_data = plot_data.assign(demean = plot_data['rides'] / plot_data['first'])

Dropping 8 id, 252 obs invariant to DNC

In [88]:
chart = px.line(plot_data, x='date', y='demean', 
        line_dash='nearby', facet_row='transit',
        color_discrete_sequence=['black'],
        title= 'Rides (normalized to starting date)',
        labels={'date':'', 'demean':'',
                'nearby':'Near DNC'},
        template='simple_white')
chart.add_vrect(x0="2024-08-19", x1="2024-08-22", 
                fillcolor="gray", opacity=.5)
chart.write_image(parallel_out)
!cp {parallel_out} ../../../../eric-mc2-cv/static/img
chart.show()

# Placebo Test

In [89]:
def placebo_data(df, transit):
    df = df.loc[df.transit == transit]
    df = df.loc[df.date < "2024-08-19"]
    df = df.sort_values('date')
    df['time'] = pd.Categorical(df['date']).codes
    # Compute windows for placebo dates
    window_size = 4 # days
    n_windows = 31 // window_size
    df['windows'] = (df['time'].max() - df['time']) // window_size # count backwards
    pre = n_windows + 1 - df['windows'].clip(lower=0, upper=n_windows+1) # count forwards
    df['pre'] = pre.astype(str)
    # df['pre_label'] = (df['time'].max() - df.groupby('pre')['time'].transform('min')).astype(str)
    df = df.loc[df.groupby('pre')['UCMP'].transform('nunique') == 2] # some dont have data
    return df

def model_placebo(df, transit):
    unit_obs = df.groupby('id').size()
    df['weight'] = df['id'].map(unit_obs).apply(lambda x: 1/x)
    dist_terms = ['log_train_distance','log_bike_distance','log_bus_distance']
    dist_terms = [c for c in dist_terms if c in df.columns and transit not in c]
    dist_term = " + ".join(dist_terms)
    dist_term = dist_term if dist_term else "1"
    formula = f"""np.log1p(rides) ~ 
                UCMP * C(pre) +
                time + C(dotw) + monthofyear +
                {dist_term} +
                lat + long + I(lat * long) +
                I(lat**2) + I(long**2)
                """
    model = sm.WLS.from_formula(formula, df, weights=df['weight']).fit(cov_type='cluster',cov_kwds={'groups': df['id']})
    return model

In [90]:
model_data = placebo_data(panel, 'train')
train_pt_model = model_placebo(model_data, 'train')
model_data = placebo_data(panel, 'bike')
bike_pt_model = model_placebo(model_data, 'bike')
model_data = placebo_data(panel, 'uber')
uber_pt_model = model_placebo(model_data, 'uber')

In [91]:
constraints = [x for x in uber_pt_model.model.exog_names if 'UCMP:C(pre)' in x]
print(uber_pt_model.f_test(','.join([f"({c} = 0)" for c in constraints])))

constraints = [x for x in train_pt_model.model.exog_names if 'UCMP:C(pre)' in x]
print(train_pt_model.f_test(','.join([f"({c} = 0)" for c in constraints])))

constraints = [x for x in bike_pt_model.model.exog_names if 'UCMP:C(pre)' in x]
print(bike_pt_model.f_test(','.join([f"({c} = 0)" for c in constraints])))

<F test: F=1.2072309466874562, p=0.3021739178113289, df_denom=103, df_num=8>
<F test: F=1.7922871933259747, p=0.14136080469849846, df_denom=19, df_num=8>
<F test: F=3.8584354094167326, p=0.0004452050260568286, df_denom=121, df_num=8>

In [92]:
regs = [x for x in bike_pt_model.model.exog_names if 'UCMP:C(pre)' in x] + \
    [x for x in train_pt_model.model.exog_names if 'UCMP:C(pre)' in x] + \
    [x for x in uber_pt_model.model.exog_names if 'UCMP:C(pre)' in x]
headers = ["PT (Uber)", "PT (Train)", "PT (Bike)"]
pt_summary = summary_col([uber_pt_model, train_pt_model, bike_pt_model], 
            model_names=headers,
            info_dict={"N":lambda x:(x.nobs)},
            stars=True,
            regressor_order=sorted(list(set(regs))),
            drop_omitted=True)

pt_summary = tabulate(pt_summary.tables[0],
                   headers=[""] + headers,
                   showindex=True,
                   tablefmt='github')
# with open(pt_table_out,"w") as f:
#     f.write(pt_summary)
# !cp $pt_table_out "$cv_dir/uploads"
print(pt_summary)

|                  | PT (Uber)   | PT (Train)   | PT (Bike)   |
|------------------|-------------|--------------|-------------|
| UCMP:C(pre)[T.1] | 0.0540      | -0.7843      | -0.2338***  |
|                  | (0.0480)    | (0.5066)     | (0.0637)    |
| UCMP:C(pre)[T.2] | 0.0450      | -0.7523      | 0.0114      |
|                  | (0.0425)    | (0.5370)     | (0.0692)    |
| UCMP:C(pre)[T.3] | 0.0856**    | -0.7438      | 0.3046**    |
|                  | (0.0404)    | (0.5456)     | (0.1207)    |
| UCMP:C(pre)[T.4] | -0.0059     | -0.7913      | 0.1269      |
|                  | (0.0473)    | (0.5456)     | (0.1142)    |
| UCMP:C(pre)[T.5] | 0.0941*     | -0.7996      | 0.6823***   |
|                  | (0.0517)    | (0.5393)     | (0.2500)    |
| UCMP:C(pre)[T.6] | -0.0406     | -0.0850      | 0.4201**    |
|                  | (0.0426)    | (0.2317)     | (0.1997)    |
| UCMP:C(pre)[T.7] | 0.0096      | 0.3799       | 0.5566***   |
|                  | (0.0384)    | (0.5562)     | (0.1435)    |
| UCMP:C(pre)[T.8] | 0.0489      | 0.3642       | 0.1200      |
|                  | (0.0385)    | (0.5647)     | (0.1365)    |
| R-squared        | 0.5216      | 0.4894       | 0.5414      |
| R-squared Adj.   | 0.5190      | 0.4748       | 0.5392      |
| N                | 5685.0      | 1080.0       | 6144.0      |